### ISSUE TITLE
Bug ?

### ISSUE THREAD

**Issue by tabam1** [DoctorMcKay/node-globaloffensive#24]
If i login account, and this account logout and disconnectedFromGC with reason 2 (NO_SESSION), steam-user login again this account, but i not get connectedToGC :/

**Comment by tabam1** [comment]
Maybe i need after lost session `new GlobalOffensive(user)`

**Comment by DoctorMcKay** [comment]
I believe this is caused by the fact that Steam does not relay client disconnections to the GC, thus the GC doesn't even know that you were gone. So when you log back in again, the GC believes that you were always connected and thus it doesn't start a new session.

I don't know of a way to work around this beyond sending a message to the GC and seeing if it responds.

**Comment by tabam1** [comment]
Maybe need to restart the game:
`client.gamesPlayed([730]);`
or run other game and later 730 eg.
`client.gamesPlayed([570]);
setTimeout(function(){
    client.gamesPlayed([730]);
}, 5000);`

**Comment by DoctorMcKay** [comment]
Restarting the game might work, though you don't need to run some other game first. Use `client.gamesPlayed([])` to stop playing anything, then wait a few seconds and start 730 again.

Using `client.gamesPlayed([730])` while you're already playing CS:GO will have no effect.
