### ISSUE TITLE
Inconsistent availability state

### ISSUE THREAD

**Issue by Luluno01** [DoctorMcKay/node-globaloffensive#37]
# Problem description

The documentation requires users try to do nothing before receiving the `connectedToGC` event. At the same time it requires users to call methods only when the `haveGCSession` is `true`.

However, I noticed that I can actually send item inspect queries and receive responses from the server when `haveGCSession` is `false`.

Now I have to explain why my `haveGCSession` property is `false` and that's actually another issue:

I called `user.gamesPlayed(730)` for the first time, and received `connectedToGC` event as expected. I checked the `haveGCSession` property, it was also `true` as expected. Later, I called `user.gamesPlayed([])`, the `disconnectedFromGC` event did not fired but `haveGCSession` became `false`. I also called `inspectItem` after that, no response received (that is what I expected). Finally, I called `user.gamesPlayed(730)` again and:

1. No `connectedToGC` event fired
2. `haveGCSession` was still `false`

I was confused, so I called `inspectItem` to see what would happen, and I received responses to the inspect query.

Also, there could be a connection leak caused by the aforementioned operation sequence as mentioned [here](https://github.com/DoctorMcKay/node-steam-user/issues/277).

**Comment by DoctorMcKay** [comment]
I'm going to close this, because this is a consequence of how GC connections work. Basically, saying that you have a "connection" to the GC is kind of wrong. It's more of a UDP type of thing rather than a TCP type of thing. Messages get sent to the GC via Steam and Steam essentially just passes them along as-is. There is no concept of a "connection", only GC sessions.

It seems that sometimes when you go out-of-game, Steam doesn't relay that along to the GC so the session is not terminated. In that case, the GC just waits for the session to time out, I suppose. Sending a request while out-of-game doesn't work because Steam won't relay a message to a GC unless you're in that game.

You then go in-game and the GC never saw you as having left. `connectedToGC` will eventually get emitted because a new session will be negotiated, but your old session is actually still valid.

Regardless, even if there is technically an active session, I would rather keep the documentation saying that you need to wait for `connectedToGC`, to prevent confusion.

**Comment by Luluno01** [comment]
@DoctorMcKay Thanks for your explanation! My workaround is to fully relogin and reconnect when user becomes offline or when GC disconnects to ensure a valid GC session.
