### ISSUE TITLE
Any way to get CS:GO friend codes ?

### ISSUE THREAD

**Issue by RazenIW** [DoctorMcKay/node-globaloffensive#53]
I didn't find it anywhere in the docs, is there a way to get it using this plugin ?

**Comment by DoctorMcKay** [comment]
I realize that you closed this, but for anyone else who may be reading it, no. Friend codes are generated in the CS:GO client based on some algorithm; they aren't generated by the GC so this module would not be capable of retrieving them.

I haven't bothered to try to figure out what the algorithm is, but let me just say that *of course* the CS:GO would build their own "friend codes" thing rather than using Steam account IDs like Dota or Steam profile link IDs like https://s.team/p/drbc-nfp.
