### ISSUE TITLE
connect to GC while locally running CSGO?

### ISSUE THREAD

**Issue by Andrew3019** [DoctorMcKay/node-globaloffensive#60]
Can you connect to the CSGO GC using this and do some storage unit stuff while still actually running CSGO locally, and have the storage unit changes be present in both the local CSGO and the NodeJS CSGO?

**Comment by DoctorMcKay** [comment]
No, that's not possible with this module. Maybe you could figure out a way to inject into the CS:GO client and send messages that way, but then you might run a risk of getting VAC banned or something.

In any case, you can't do it with this module since Steam only lets you be in-game on one client at a time.
